import = ["~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"]

[window]
startup_mode = "Maximized"
decorations = "None"
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14
